# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-26 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=13)),
                ('password', models.CharField(max_length=24)),
                ('avator_url', models.CharField(max_length=200)),
                ('nick_name', models.CharField(max_length=20)),
            ],
        ),
    ]
