# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-26 14:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20180826_2219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='avator_url',
            new_name='avatar_url',
        ),
    ]
