# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-03 14:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='image_url',
            new_name='imageUrl',
        ),
    ]
